/**
 * Command parser + per-shape gating for the Telegram control surface.
 *
 * Phase 1 command matrix:
 *
 *   | Command               | Available on shape  | Notes                       |
 *   |-----------------------|---------------------|-----------------------------|
 *   | /start <agent>        | all (placeholder)   | Phase 1 = pre-registered    |
 *   | /agents               | all                 | Lists all registered handles|
 *   | /approve_allow_<id>   | n/a (callback form) | Inline-keyboard callback    |
 *   | /approve_deny_<id>    | n/a (callback form) | Inline-keyboard callback    |
 *   | /approve <id> allow   | n/a                 | Text-form alternative       |
 *   | /abort <agent>        | all                 |                             |
 *   | /inject <agent> ...   | pty ONLY            | Shape 1 only — gated        |
 *   | /status <agent>       | all                 |                             |
 *
 * Phase 3+ adds `/send <agent> <message>` for non-PTY shapes. The
 * `isCommandAvailableForShape` gating logic is in place from Phase 1 so
 * that adding new shapes is a pure rules-table edit, not a routing
 * rewrite.
 *
 * Callback-form rename note (Plan 06 stress-test PR3): the cortextOS
 * upstream uses `appr_*` callback IDs. iaGO renames to `approve_allow_*`
 * / `approve_deny_*` for clarity and to match the text-form `/approve`
 * command. Bot code MUST emit the `approve_*` form on inline keyboards;
 * the legacy `appr_*` form is NOT accepted.
 */

import type { AgentShape } from "../agent-runtime/types.js";
import { isValidApprovalId } from "./approval-bus.js";

export type Command =
	| { readonly name: "start"; readonly agent: string }
	| { readonly name: "agents" }
	| {
			readonly name: "approve";
			readonly approvalId: string;
			readonly decision: "allow" | "deny";
	  }
	| { readonly name: "abort"; readonly agent: string }
	| { readonly name: "inject"; readonly agent: string; readonly text: string }
	| { readonly name: "status"; readonly agent: string };

export type ParseResult =
	| { readonly ok: true; readonly command: Command }
	| { readonly ok: false; readonly error: string };

export type ShapeGateResult =
	| { readonly available: true }
	| { readonly available: false; readonly reason: string };

const APPROVE_CALLBACK_PREFIX_ALLOW = "/approve_allow_";
const APPROVE_CALLBACK_PREFIX_DENY = "/approve_deny_";

function tokenize(text: string): string[] {
	return text.trim().split(/\s+/);
}

export function parseCommand(text: string): ParseResult {
	if (typeof text !== "string" || text.length === 0) {
		return { ok: false, error: "empty command" };
	}
	const trimmed = text.trim();
	if (trimmed.length === 0) {
		return { ok: false, error: "empty command" };
	}

	// Inline-keyboard callback form for approvals: leading slash optional
	// because Telegram callback_data does not require it. Accept both.
	// Telegram callback_data has no leading slash by convention (bot.ts
	// sendApprovalRequest emits `approve_allow_<id>` form); commands.ts
	// prepends one for symmetry with text /commands so the same prefix
	// match handles both surfaces.
	const callbackBody = trimmed.startsWith("/") ? trimmed : `/${trimmed}`;
	if (callbackBody.startsWith(APPROVE_CALLBACK_PREFIX_ALLOW)) {
		const id = callbackBody.slice(APPROVE_CALLBACK_PREFIX_ALLOW.length);
		if (id.length === 0) {
			return { ok: false, error: "missing argument: approvalId" };
		}
		// SECURITY (PR45 critical): callback_data is untrusted user input.
		// Reject anything that is not the exact UUID v4 form generated by
		// `crypto.randomUUID()` — closes the path-traversal surface in
		// `resolveApproval` that would let an allowlisted user delete or
		// overwrite arbitrary files under the daemon state root.
		if (!isValidApprovalId(id)) {
			return { ok: false, error: "invalid approval ID" };
		}
		return {
			ok: true,
			command: { name: "approve", approvalId: id, decision: "allow" },
		};
	}
	if (callbackBody.startsWith(APPROVE_CALLBACK_PREFIX_DENY)) {
		const id = callbackBody.slice(APPROVE_CALLBACK_PREFIX_DENY.length);
		if (id.length === 0) {
			return { ok: false, error: "missing argument: approvalId" };
		}
		if (!isValidApprovalId(id)) {
			return { ok: false, error: "invalid approval ID" };
		}
		return {
			ok: true,
			command: { name: "approve", approvalId: id, decision: "deny" },
		};
	}

	if (!trimmed.startsWith("/")) {
		return { ok: false, error: "unknown command: <not a command>" };
	}

	const tokens = tokenize(trimmed);
	const head = tokens[0];
	if (head === undefined) {
		return { ok: false, error: "empty command" };
	}
	const cmd = head.slice(1);

	switch (cmd) {
		case "start": {
			const agent = tokens[1];
			if (agent === undefined) {
				return { ok: false, error: "missing argument: agent" };
			}
			return { ok: true, command: { name: "start", agent } };
		}
		case "agents": {
			return { ok: true, command: { name: "agents" } };
		}
		case "approve": {
			const id = tokens[1];
			const decision = tokens[2];
			if (id === undefined) {
				return { ok: false, error: "missing argument: approvalId" };
			}
			if (decision === undefined) {
				return { ok: false, error: "missing argument: decision" };
			}
			if (decision !== "allow" && decision !== "deny") {
				return { ok: false, error: `invalid decision: ${decision}` };
			}
			// SECURITY (PR45 critical): text-form /approve accepts user
			// input. UUID-strict validation closes the path-traversal
			// surface — see comment in callback-form branch above.
			if (!isValidApprovalId(id)) {
				return { ok: false, error: "invalid approval ID" };
			}
			return {
				ok: true,
				command: { name: "approve", approvalId: id, decision },
			};
		}
		case "abort": {
			const agent = tokens[1];
			if (agent === undefined) {
				return { ok: false, error: "missing argument: agent" };
			}
			return { ok: true, command: { name: "abort", agent } };
		}
		case "inject": {
			// Preserve whitespace (newlines, repeated spaces, tabs) in the
			// inject payload by slicing the ORIGINAL input rather than
			// re-joining tokens — `tokens.join(" ")` collapses every run of
			// whitespace to a single space, which silently rewrites the
			// user's multi-line payload before it reaches the PTY adapter.
			const INJECT_PREFIX = "/inject";
			const afterCmd = trimmed.slice(INJECT_PREFIX.length).trimStart();
			if (afterCmd.length === 0) {
				return { ok: false, error: "missing argument: agent" };
			}
			// Split agent from payload on the FIRST whitespace of ANY kind
			// (space, tab, newline) to match tokenize()'s `\s+` semantics — a
			// literal indexOf(" ") regressed tab/newline-separated invocations
			// to "missing argument: text". The agent id forbids whitespace, so
			// the first whitespace is always the agent/text boundary; slicing
			// at firstWs+1 drops that one separator and preserves the rest of
			// the payload (including its own whitespace) verbatim.
			const firstWs = afterCmd.search(/\s/);
			if (firstWs === -1) {
				return { ok: false, error: "missing argument: text" };
			}
			const injectAgent = afterCmd.slice(0, firstWs);
			const injectText = afterCmd.slice(firstWs + 1);
			if (injectText.length === 0) {
				return { ok: false, error: "missing argument: text" };
			}
			return {
				ok: true,
				command: { name: "inject", agent: injectAgent, text: injectText },
			};
		}
		case "status": {
			const agent = tokens[1];
			if (agent === undefined) {
				return { ok: false, error: "missing argument: agent" };
			}
			return { ok: true, command: { name: "status", agent } };
		}
		default: {
			return { ok: false, error: `unknown command: ${head}` };
		}
	}
}

/**
 * Per-shape command gating.
 *
 * `getShape` resolves the registered shape for the given `agentId`,
 * returning `null` when the agent is not registered. Commands that name
 * an agent (`start`, `abort`, `inject`, `status`) require a registered
 * shape; the `/agents` and `/approve` commands are global.
 *
 * Phase 1 — only `pty` is registered, but `/inject` is gated to that
 * shape so Phase 3+ adapters (HTTP, MCP, event, daemon) require the
 * forthcoming `/send` command instead.
 */
export async function isCommandAvailableForShape(
	command: Command,
	getShape: (agent: string) => Promise<AgentShape | null>,
): Promise<ShapeGateResult> {
	switch (command.name) {
		case "agents":
		case "approve":
			return { available: true };
		case "start":
		case "abort":
		case "status": {
			const shape = await getShape(command.agent);
			if (shape === null) {
				// PR45 M5: truncate user-supplied agent name to 64 chars in
				// the reason text — the bot embeds this in a Telegram reply
				// and unbounded user input lets an allowlisted attacker
				// stuff arbitrary text into the chat history.
				return {
					available: false,
					reason: `agent not registered: ${command.agent.slice(0, 64)}`,
				};
			}
			return { available: true };
		}
		case "inject": {
			const shape = await getShape(command.agent);
			if (shape === null) {
				return {
					available: false,
					reason: `agent not registered: ${command.agent.slice(0, 64)}`,
				};
			}
			if (shape !== "pty") {
				return {
					available: false,
					reason: `/inject is only available for shape "pty" (agent ${command.agent.slice(0, 64)} is shape "${shape}")`,
				};
			}
			return { available: true };
		}
	}
}
